# Global settings
source global-config.conf
source family-rv1106.conf

# Board-specific
BOARD=luckfox-pico-mini
ENABLE_EXTENSIONS="$ENABLE_EXTENSIONS,perf-journald,perf-sources,perf-sysctl,perf-tmp-rootfs"
